### ISSUE TITLE
Traceback (most recent call last):   File "/home/hrq/./dynamicwallpaperconverter", line 186, in <module>     prepare_metadata(input_file, working_directory, options)   File "/home/hrq/./dynamicwallpaperconverter", line 141, in prepare_metadata     kind, metadata = extract_metadata(input_file)                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/hrq/./dynamicwallpaperconverter", line 68, in extract_metadata     kind, base64_metadata = extract_base64_metadata(input_file)                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/hrq/./dynamicwallpaperconverter", line 64, in extract_base64_metadata     raise MetadataException("No metadata found") MetadataException: No metadata found

### ISSUE THREAD

**Issue by hrqmonteiro** [zzag/plasma5-wallpapers-dynamic#134]
Trying to convert [this](https://store.kde.org/p/1433516) wallpaper, which is in .heic using the tool.

Doesn't work at all.

```
./dynamicwallpaperconverter --crossfade wallpaper.heic          
Traceback (most recent call last):
  File "/home/hrq/./dynamicwallpaperconverter", line 186, in <module>
    prepare_metadata(input_file, working_directory, options)
  File "/home/hrq/./dynamicwallpaperconverter", line 141, in prepare_metadata
    kind, metadata = extract_metadata(input_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrq/./dynamicwallpaperconverter", line 68, in extract_metadata
    kind, base64_metadata = extract_base64_metadata(input_file)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hrq/./dynamicwallpaperconverter", line 64, in extract_base64_metadata
    raise MetadataException("No metadata found")
MetadataException: No metadata found
```

**Comment by zzag** [comment]
It looks like that wallpaper was made for an older version of this plugin. Try installing v3, https://github.com/zzag/plasma5-wallpapers-dynamic/releases/tag/3.3.9; or if you have the source files, make one for v4
